[build]
  command = "python -m pip install --upgrade pip && python -m pip install mkdocs mkdocs-material && python -m mkdocs build"
  publish = "site"

[build.environment]
  PYTHON_VERSION = "3.11"

[[redirects]]
  from = "/"
  to = "/landing/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/index.html"
  to = "/landing/index.html"
  status = 200
  force = true

[context.deploy-preview]
  [context.deploy-preview.headers]
    for = "/*"
    [context.deploy-preview.headers.values]
      X-Robots-Tag = "noindex, nofollow"

[[redirects]]
  from = "https://merry-donut-2152a4.netlify.app/*"
  to = "https://bt2c.net/:splat"
  status = 301
  force = true

# Clean slugs for key docs pages
[[redirects]]
  from = "/whitepaper"
  to = "/whitepaper/bit2coin_whitepaper/"
  status = 301

[[redirects]]
  from = "/snapshot"
  to = "/launch/snapshot_policy/"
  status = 301

[[redirects]]
  from = "/runbook"
  to = "/launch/snapshot_day/"
  status = 301

[[redirects]]
  from = "/announcement"
  to = "/announcements/snapshot_announcement/"
  status = 301

[[redirects]]
  from = "/treasury"
  to = "/launch/treasury_policy/"
  status = 301

[[redirects]]
  from = "/security"
  to = "/SECURITY/"
  status = 301

[[redirects]]
  from = "/explorer"
  to = "/explorer/"
  status = 301

[[redirects]]
  from = "/genesis"
  to = "/genesis/params/"
  status = 301
