[build]
  command = "python -m pip install --upgrade pip && python -m pip install -r requirements-docs.txt && python -m mkdocs build"
  publish = "site"

[build.environment]
  PYTHON_VERSION = "3.11"

[[redirects]]
  from = "/"
  to = "/landing/index.html"
  status = 200
