[build]
  command = "python -m pip install --upgrade pip && python -m pip install mkdocs mkdocs-material && python -m mkdocs build"
  publish = "site"

[build.environment]
  PYTHON_VERSION = "3.11"

[[redirects]]
  from = "/"
  to = "/landing/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/index.html"
  to = "/landing/index.html"
  status = 200
  force = true

[context.deploy-preview]
  [context.deploy-preview.headers]
    for = "/*"
    [context.deploy-preview.headers.values]
      X-Robots-Tag = "noindex, nofollow"

[[redirects]]
  from = "https://merry-donut-2152a4.netlify.app/*"
  to = "https://bt2c.net/:splat"
  status = 301
  force = true
